### PR TITLE
Update to 1.18.2

### PR DESCRIPTION
**Pull request by violet-sh**
Small update, just changes to mappings and updated dependencies.

### CODE REVIEW

**Comment by LambdAurora** [comment]
Weird, I thought I already switched to Quilt Mappings, eh, doesn't matter.

**Comment by LambdAurora** [comment]
Thank you for your contribution!

**Comment by violet-sh** [comment]
>  I thought I already switched to Quilt Mappings

Interestingly I thought you had too until looking at it lol. I can always migrate it if you want.

**Comment by LambdAurora** [comment]
Eh, if you're up for it feel free!
I just hope the world-related stuff LambdaMap uses is mapped under QM.

**Pull request merged**
